// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace lab3trspo
{
    internal sealed partial class Vsix
    {
        public const string Id = "lab3trspo.f99ad44f-3302-4377-93e5-00a3db01e98d";
        public const string Name = "lab3trspo";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Артур Хасанов";
        public const string Tags = "";
    }
}
